# Default values for rosa_uplift lab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployer:
  domain: REPLACEME-OPENSHIFT_DOMAIN-uplift
  apiUrl: https://api.cluster.opentlc.com:6443

user:
  count: 2
  base: user

content:
  mode: workshop # or demo

ossm:
  deployResources: false # false for workshop mode

istio_cp_namespace: istio-system
windows_mesh_namespace_base: windowsmesh
windows_networking_namespace_base: windowsnetworking
vms_image_url: http://s3.us-east.cloud-object-storage.appdomain.cloud/roadshowocpvirt
# vms_image_url: https://catalog-item-assets.s3.us-east-2.amazonaws.com/qcow_images
vms_start_vms: "true"
vms_run_strategy: "RerunOnFailure"
vms_machine_type: q35

ossm_vms_servicemeshmember_create: "false"
ossm_vms_sidecar_inject: "false"
ossm_vms_proxy_config: "false"
ossm_vms_service_discovery: "true"
ossm_vms_service_discovery_label: "app: winmesh"
ossm_vms_label_versions: "true"

ingressgatway_url_path: https://localhost
# add clouds here like aws, azure, gcp, rosa, etc.
# and add updates to the templates/ to support them
cloud: rosa
