{{- define "loadmaker.app" -}}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: loadmaker
  namespace: {{ .Values.windows_mesh_namespace_base }}-user{{ .user_index }}
  # namespace: windowsmesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadmaker
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: loadmaker
    spec:
      containers:
        - name: container
          image: bunchjesse/loadtest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: REQUESTS_PER_SECOND
              value: '2'
            - name: DURATION
              value: '10000'
            - name: URL
              # value: 'http://istio-ingressgateway-istio-system.apps.virt-cluster.vew1.p1.openshiftapps.com'
              value: 'https://user{{ .user_index }}-istio-system.{{ .Values.deployer.domain }}'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
{{- end -}}
